### ISSUE TITLE
Flask deprecating etags for file objects

### ISSUE THREAD

**Issue by unixnation** [divad/bargate#57]
An alert in the following format is logged in the application log file:

`/<path>/<to>/<application>/bargate/smb.py:388: DeprecationWarning: In future flask releases etags will no longer be generated for file objects passed to the send_file function because this behavior was unreliable.  Pass filenames instead if possible, otherwise attach an etag yourself based on another value`

Need to check if usage of the etags have been removed in a later release of Bargate.

Generated with Flask 0.10.1.

**Comment by divad** [comment]
We can't pass a file name to flask.send_file because that only works for files on the local system, we pass in a fp-like object (the SMB connection's file handle).
