### ISSUE TITLE
Show filename of file to be deleted in confirmation dialogue

### ISSUE THREAD

**Issue by unixnation** [divad/bargate#58]
Request from an end user, which seems reasonable

When asking a user to confirm deletion of a file., it would be useful to include the filename in the confirmation request, to reassure me that I have selected the correct file.

Currently it just asks "Are you sure you want to permanently delete the file?", with no indication of which file has been selected. When the confirmation dialogue is displayed, the page resets to the top with the result that a file list longer than a single screen hides the selected file.

The confirmation dialogue should display the filename of the item to be deleted.

**Comment by divad** [comment]
Confirmed feature request, will patch stable and dev branches.
