### ISSUE TITLE
Overwriting files with a smaller file size leaves garbage at end of file

### ISSUE THREAD

**Issue by unixnation** [divad/bargate#59]
Appears to be a problem overwriting files in that data will only be written up to the size of the original file, resulting in potential data loss.

How should this be resolved - should we write the data to _filename_ followed by some random string then unlink the original file and rename the new file for example?

**Comment by divad** [comment]
Investigating now. I'm hoping this is just a bug in the python code rather than in pysmbc, I guess if it is a bug in that then we'd upload to filename.new and then rename as you say. Thats a pretty typical pattern for saving files on a filesystem (but we're saving over SMB so I really shouldn't have to do that!)

**Comment by divad** [comment]
So I can't re-create this bug - I uploaded a test file, read it correctly, then uploaded a much larger file, and could still read it fully.

Can you give me some more information, e.g. what was the back end SMB server software and version, what was the file type you were uploading? Any chance of sending me a test file?

**Comment by divad** [comment]
I've tried several different file formats (not that it should make any difference) and I cannot recreate the problem against Samba or OneFS using latest stable bargate.

**Comment by unixnation** [comment]
That's interesting - I'll double check where the user who reported this has their home directory but we were able to reproduce this against a Windows Server 2012 R2  fileserver.

If there's an issue in a dependency that has been fixed it's highly likely we've not installed the  patch (due to the SMB client issues Red Hat introduced making us a bit cautious)!

**Comment by divad** [comment]
I will get a 2012 R2 file server set up as a test and get back to you!

**Comment by divad** [comment]
I've tested against a domain-bound Windows Server 2012 R2 file server and I cannot re-create the problem there either.

If there is a problem it must be a samba (libsmbclient) or server problem - but my money is on the server. What file system is the back end server using?

**Comment by unixnation** [comment]
Ok, I'm an idiot! This I'll teach me not to write bug reports from memory on the train. The problem is actually slightly different to what I described.... :(

I've just re-tested this - what appears to happen in testing with small plain text files is as follows:
* Creating a test text file of one short line then **overwriting** with a longer file **works** as expected.
* Overwriting with a **shorter** text file doesn't seem to work - the file isn't truncated to the new length.
 * Selecting the overwritten file and choosing to **view** via the web interface, it appears unchanged.
 * Choose to **download** the file rather than view it and the content of the new file does appear to be there but the original file is appended. The file is exactly the same number of bytes as it was before it was overwritten.

> What file system is the back end server using?

It's just NTFS.

You can shoot me now.

**Comment by divad** [comment]
So its the opposite way around to what you said? :P

**Comment by divad** [comment]
Commit https://github.com/divad/bargate/commit/b09308091bbe9097afa7e00388ebb41a5bf30192 fixes this issue. Will be released in 1.3.2 when I've fixed the other issues.
