### ISSUE TITLE
Request to add simple filename search facility

### ISSUE THREAD

**Issue by JakeDovey** [divad/bargate#87]
We have users who would like a search facility added to this system. Is this feasible?

Cheers,

Jake
IRT

**Comment by divad** [comment]
The code to do this is now about 50% complete.

**Comment by divad** [comment]
The code to do this is now about 80% complete.

**Comment by divad** [comment]
The 1.4.1 release candidate is out which implements basic file searching.

I will inform you when 1.4.1 is available on fwa.soton.ac.uk

**Comment by divad** [comment]
Resolved in v1.4.1
